### ISSUE TITLE
usage with feathersjs authentication module on react-native

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers-localstorage#16]
Hi

   How could I use AsyncStorage with the feathersjs authentication service on react-native.
I used to do:
```
this.app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      // Use AsyncStorage to store our login toke
      .configure(authentication({
        storage: AsyncStorage
      }));
  }
```
but it doesn't work anymore with RN 0.30 and latest feathers client api

I tried
```
import localstorage from 'feathers-localstorage';
this.app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      .use('/auth', localstorage({ storage: AsyncStorage }));
```
but it doesn't work either (return an error: _this2.app.authenticate is not a function)

**Comment by daffl** [comment]
feathers-localstorage is a service wrapper for Async- or Localstorage and not used in the authentication module (anymore). Are you getting any errors using

```js
const app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      // Use AsyncStorage to store our login toke
      .configure(authentication({
        storage: AsyncStorage
      }));
```

How are you using this setup?

**Comment by ramsestom** [comment]
No I don't get any error using this. But it doesn't seem to work anymore as the authentication is not stored (I have to re-authenticate each time I restart the app whereas with previous version of react native it was working as expected and the authentication token was correctly stored)
