### ISSUE TITLE
Using without explicitly passing a storage engine is throwing an error with Webpack/Browserify

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-localstorage#3]
@naptiv reported this in https://github.com/feathersjs/feathers-authentication/issues/84:

> Btw, I had to change .use('storage', localstorage({"storage":memory})) as I got a ReferenceError: window is not defined at new LocalStorage @feathers-localstorage/lib/index.js:32:41

**Comment by ekryski** [comment]
@naptiv are you using webpack or babel? I'm wondering if it is a shimming issue.

Maybe we shouldn't be expecting window to just be there and instead you **always** get the developer to pass in their storage engine explicitly. cc/ @daffl

**Comment by naptiv** [comment]
@ekryski webpack based on this boilerplate https://github.com/RickWong/react-isomorphic-starterkit

**Comment by ekryski** [comment]
Ya the issue is that with webpack you need to shim the `window` object. So you end up with something like this in your config.

```js
externals: [
        {
            "window": "window"
        }
    ],
```

Not sure how I want to proceed here. I think it actually might be more flexible and work "out of the box" better if we explicitly get people to pass in their storage engine.

**Comment by daffl** [comment]
We should probably also set https://github.com/feathersjs/feathers-localstorage/blob/master/src/index.js#L7 to

```js
this._storage = options.storage || (typeof window !== 'undefined' && window.localStorage);
```

**Comment by daffl** [comment]
And then throw an error if `this._storage` is undefined.

**Comment by ekryski** [comment]
Ya I think you're right @daffl
